"""control de procesamiento

Revision ID: b696444a1e17
Revises: 68d7bc8eefc4
Create Date: 2026-10-02 13:54:39.072015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b696444a1e17'
down_revision: Union[str, Sequence[str], None] = '68d7bc8eefc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentos', sa.Column('progreso', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documentos', sa.Column('intentos', sa.Integer(), server_default='0', nullable=False))
    op.add_column('documentos', sa.Column('iniciado_en', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentos', 'iniciado_en')
    op.drop_column('documentos', 'intentos')
    op.drop_column('documentos', 'progreso')
    # ### end Alembic commands ###
